branches:
  only:
  - master
language: python
python:
  - "3.6.7"
install:
  - "pip install -r requirements.txt"
script:
    pytest --black --cov=./app --cov-report=term-missing
after_success:
  - COVERALLS_REPO_TOKEN=OCnCvZcuMaoo60vGu8fHIzpxzT6W1kypT coveralls