branches:
  only:
  - master
language: python
python:
  - "3.6.7"
env:
  global:
  - COVERAGE=1
install:
  - "pip install -r requirements.txt"
script:
  - if [ -z $COVERAGE ] ; then
      pytest;
    else
      pytest --pep8 --cov=./app --cov-report=term-missing;
    fi
after_success:
  - coveralls