name: Pytest Coveralls Coverage
on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.6.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.6.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        pytest --black --cov=./app --cov-report=term-missing
